services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Richtextinputfields\:
    resource: '../Classes/*'

  B13\Richtextinputfields\EventListener\TcaToRteConfiguration:
    tags:
      - name: event.listener
        identifier: 'b13/richtextinputfields/tca-to-rte-configuration'
