services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  B13\Richtextinputfields\:
    resource: '../Classes/*'

  B13\Richtextinputfields\EventListener\TcaToRteConfiguration:
    tags:
      - name: event.listener
        event: TYPO3\CMS\RteCKEditor\Form\Element\Event\AfterPrepareConfigurationForEditorEvent
